language: python

notifications:
  email:
    recipients:
      - alexandra.diem@gmail.com
    on_success: never   # default: change
    on_failure: never  # default: always

matrix:
    include:
        - os: linux
          python: 3.6.7


install:
  - sudo apt-get update

  # Install conda
  - wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda

  # Export path
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  # Set conda parameters
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge

  # Set up environment
  - conda create -n fenics-geometry

  # Activate environment
  - source activate fenics-geometry fenics
  - pip uninstall h5py
  - pip install -r requirements.txt
  - python setup.py install

  # Useful for debugging any issues with conda
  - conda info -a

script:
  - pytest tests/
